### ISSUE TITLE
MongoDB not supported

### ISSUE THREAD

**Issue by panosru** [serjoscha87/cockpit_GROUPS#7]
![image](https://user-images.githubusercontent.com/400362/51640070-3bfe6400-1f6b-11e9-8ef5-01110a2983cb.png)

![image](https://user-images.githubusercontent.com/400362/51640090-44ef3580-1f6b-11e9-9e72-9be07879519b.png)

Seems that the plugin is intended to work with sqlite since in mongo you cannot have a key that contains a dot symbol.

Do you plan to support Mongo?

Thanks!

**Comment by serjoscha87** [comment]
I did not run the addon within a mongo db env - so I was not planing to add support yet. I completely lost track of the cockpit internals since I did not work with them for some time - but perhaps I gonna take a look into it.

I cannot promise you a thing.

I did not even know that it makes a different. Thanks for the note.
